### ISSUE TITLE
Redirect url from Cas is not correctly constructed

### ISSUE THREAD

**Issue by GeorgeProost** [pac4j/j2e-pac4j-cdi-demo#14]
Hello,

I have an issue implementing this demo.

I have only modified the casClient to reference our CAS server.
I can show the initial page .. click on CAS .. CAS displays the login screen as expected.

After login I get a redirect to: http://localhost:8080/callback?client_name=CasClient&ticket=ST-674-htCtpLyu4coQcZexITBS-aaa-prodxxxx

Looks like the callback has not been resolved correctly.

I have seen another thread that could be similar to this issue https://github.com/pac4j/pac4j/issues/1024
Can you please guide me.

Note: the none-cdi version https://github.com/pac4j/buji-pac4j-demo works with our cas server.

Regards

George

**Comment by leleuj** [comment]
Please use the mailing list: https://groups.google.com/forum/#!forum/pac4j-users for questions.
